import os
from dotenv import load_dotenv
load_dotenv()
from careerloop.llm_chat import OnboardingAgent

def main():
    agent = OnboardingAgent()
    cv_text = """IENCE}}
{{SECTION
_
PROJECTS}}
{{PROJECTS}}
EDUCATION
M.SC. STATISTICS AND MACHINE LEARNING - LINKÖPING UNIVERSITY, SWEDEN
(2020-2022)
B.TECH COMPUTER SCIENCE AND ENGINEERING - SRM UNIVERSITY, INDIA (2016-
2020)
MASTER'S THESIS
DEVELOPED A MACHINE LEARNING PIPELINE UTILIZING AUTOENCODERS AND
CLASSIFIERS TO PREDICT COLORECTAL CANCER METASTASIS FROM RNA
SEQUENCING DATA. EMPLOYED TRANSFER LEARNING, PCA, AND NETWORK
ANALYSIS FOR BIOMARKER DETECTION IN HIGH-DIMENSIONAL BIOLOGICAL
DATASETS.
{{EDUCATION}}
{{SECTION
_
CERTIFICATIONS}}
{{CERTIFICATIONS}}
SKILLS
PROGRAMMING PYTHON · SQL
AI SYSTEMS LLM APIS · RAG PIPELINES · EMBEDDINGS · PROMPT ENGINEERING · TOOL
CALLING · MULTI-MODEL ROUTING · AGENTIC WORKFLOWS ·
LANGCHAIN/LANGGRAPH
BACKEND SYSTEMS
DESIGN
INFRA FASTAPI · REDIS (CACHING, QUEUES) · POSTGRESQL · REST APIS · ASYNC
PIPELINES · WEBSOCKETS. SSE STREAMING
STATEFUL SYSTEMS · WORKFLOW ORCHESTRATION · MEMORY SYSTEMS ·
CONTEXT MODELING · DISTRIBUTED PIPELINES
DOCKER · AWS · FLY.IO · LOGGING · TRACING · METRICS · PERFORMANCE
OPTIMIZATION
ETL PIPELINES · DATA VALIDATION · POWER BI · TABLEAU
DATA {{SKILLS}}"""

    print("Sending CV to agent...")
    data, reply, is_complete = agent.process(cv_text, {})
    print("Reply:", reply)
    print("Data keys extracted:", data.keys())

if __name__ == "__main__":
    main()
