from enum import Enum

class UserState(Enum):
    # Onboarding States
    IDLE = "IDLE"
    ONBOARDING_WAITING_CV = "ONBOARDING_WAITING_CV"
    ONBOARDING_Q1_ROLES = "ONBOARDING_Q1_ROLES"
    ONBOARDING_Q2_CITIES = "ONBOARDING_Q2_CITIES"
    ONBOARDING_Q3_SALARY = "ONBOARDING_Q3_SALARY"
    ONBOARDING_Q4_NOTICE = "ONBOARDING_Q4_NOTICE"
    ONBOARDING_Q5_MODE = "ONBOARDING_Q5_MODE"

    # Active Triage States
    DAILY_BRIEF_SENT = "DAILY_BRIEF_SENT"
    REVIEWING_JOB = "REVIEWING_JOB"
    
    # Compilation & Action States
    PACK_GENERATING = "PACK_GENERATING"
    PACK_READY = "PACK_READY"
    AWAITING_RESUME_REVIEW = "AWAITING_RESUME_REVIEW"
    AWAITING_APPLICATION_CONFIRMATION = "AWAITING_APPLICATION_CONFIRMATION"
    APPLIED = "APPLIED"

    # Feedback & Interview States
    FOLLOWUP_DUE = "FOLLOWUP_DUE"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_PREP_READY = "INTERVIEW_PREP_READY"
    POST_INTERVIEW_DEBRIEF = "POST_INTERVIEW_DEBRIEF"
